export const GADGETS = [
    {
        id: 'GDG-AXIOS-001',
        library: 'axios',
        versionRange: '>=0.8.1',
        property: 'baseURL',
        category: 'ROUTING',
        impactClass: 'SYNTHETIC_SSRF',
        description: 'Axios merges request config with defaults via Object.assign-like semantics. If Object.prototype.baseURL is set, axios inherits it and routes all requests to that base URL.',
        trigger: 'axios creates a config object that inherits from Object.prototype; if baseURL is inherited, requests route to the inherited value',
        evidence: [],
        mitigation: {
            strategy: 'Own-property check',
            description: 'Validate that baseURL is an own property of the config before use.',
            codeExample: `if (!Object.prototype.hasOwnProperty.call(config, 'baseURL')) config.baseURL = defaultBaseURL`,
            verified: false,
        },
        status: 'REPRODUCED',
        labTarget: 'http-sim',
    },
    {
        id: 'GDG-AXIOS-002',
        library: 'axios',
        versionRange: '>=0.8.1',
        property: 'method',
        category: 'HTTP',
        impactClass: 'SYNTHETIC_HTTP_MANIPULATION',
        description: 'If Object.prototype.method is polluted, axios picks up the inherited HTTP method for all requests, enabling method override attacks.',
        trigger: 'axios reads the method property from config; a polluted Object.prototype.method overrides the intended HTTP method',
        evidence: [],
        mitigation: {
            strategy: 'Explicit method assignment',
            description: 'Always explicitly set the method as an own property on every axios request config.',
            verified: false,
        },
        status: 'REPRODUCED',
        labTarget: 'http-sim',
    },
    {
        id: 'GDG-AXIOS-003',
        library: 'axios',
        versionRange: '>=0.8.1',
        property: 'headers',
        category: 'HTTP',
        impactClass: 'SYNTHETIC_HTTP_MANIPULATION',
        description: 'Polluting Object.prototype.headers causes axios to inject those headers into every outgoing request, enabling credential or context injection.',
        trigger: 'axios merges headers from config; inherited headers from Object.prototype are included in all requests',
        evidence: [],
        mitigation: {
            strategy: 'Object.create(null) config',
            description: 'Create axios configs with null prototype to prevent prototype property inheritance.',
            codeExample: `const config = Object.create(null); config.headers = { Authorization: token }`,
            verified: false,
        },
        status: 'REPRODUCED',
        labTarget: 'metadata-sim',
    },
    {
        id: 'GDG-AUTH-001',
        library: 'custom-auth-middleware',
        property: 'role',
        category: 'AUTH',
        impactClass: 'SYNTHETIC_AUTH_BYPASS',
        description: 'Authentication middleware that reads req.user.role without an own-property check is vulnerable to privilege escalation via prototype pollution.',
        trigger: "auth middleware reads req.user.role without own-property check; inherited 'role' escalates privileges",
        evidence: [],
        mitigation: {
            strategy: 'hasOwnProperty guard',
            description: "Use Object.prototype.hasOwnProperty.call(req.user, 'role') before trusting the role value.",
            codeExample: `const role = Object.prototype.hasOwnProperty.call(req.user, 'role') ? req.user.role : 'guest'`,
            verified: false,
        },
        status: 'REPRODUCED',
        labTarget: 'auth-sim',
    },
    {
        id: 'GDG-CB-001',
        library: 'custom-traversal',
        property: 'visitor',
        category: 'CALLBACK',
        impactClass: 'SYNTHETIC_EXECUTION_MARKER',
        description: 'Object traversal functions that invoke obj.visitor() as a callback without an own-property check execute arbitrary inherited functions.',
        trigger: 'object traversal function calls obj.visitor() if it exists; inherited visitor executes as a callback',
        evidence: [],
        mitigation: {
            strategy: 'Own-property callback guard',
            description: 'Check that visitor is an own function before invoking it.',
            codeExample: `if (Object.prototype.hasOwnProperty.call(obj, 'visitor') && typeof obj.visitor === 'function') obj.visitor()`,
            verified: false,
        },
        status: 'REPRODUCED',
        labTarget: 'execution-sim',
    },
    {
        id: 'GDG-NODE-001',
        library: 'node-core',
        property: 'toString',
        category: 'EXECUTION_SIM',
        impactClass: 'SYNTHETIC_EXECUTION_MARKER',
        description: 'Overriding Object.prototype.toString causes string coercions throughout Node.js runtime to invoke attacker-controlled code, marking the execution flow.',
        trigger: 'any string coercion (`${obj}`, String(obj), template literals) triggers the polluted toString, executing attacker marker code',
        evidence: [],
        mitigation: {
            strategy: 'Freeze Object.prototype',
            description: 'Use Object.freeze(Object.prototype) at startup to prevent modifications.',
            codeExample: `Object.freeze(Object.prototype)`,
            verified: false,
        },
        status: 'POTENTIAL',
    },
];
//# sourceMappingURL=gadgets.js.map